# Generated by Django 4.2.7 on 2025-10-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('regular_hours', models.FloatField(default=0)),
                ('overtime_hours', models.FloatField(default=0)),
                ('vacation_hours', models.FloatField(default=0)),
                ('sick_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Work hours',
            },
        ),
        migrations.AddConstraint(
            model_name='workhours',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='workhours_unique_employee_date'),
        ),
    ]
